export { default } from './plugin.ts'
export { MemoryPlugin, MemoryPluginConfigSchema, type MemoryPluginConfig } from './plugin.ts'
export { MemoryProtocolPlugin } from './protocol.ts'
export { MEMORY_SCHEMA_VERSION } from './persistence/migrations.ts'
export { MemoryError, MemoryService, type MemoryServiceConfig } from './service.ts'
export {
  type CandidateDecisionRequest,
  type CandidateEvidenceRequest,
  type CorrectMemoryRequest,
  type ForgetMemoryRequest,
  type MemoryConflict,
  type MemoryEvidence,
  type MemoryEvidenceInput,
  type MemoryEvidenceRelation,
  type MemoryKind,
  type MemoryRecord,
  type MemoryRevision,
  type MemoryRole,
  type MemoryScope,
  type MemorySearchRequest,
  type MemorySearchResult,
  type MemoryStatus,
  type MemoryTemporalInput,
  type ObserveMemoryRequest,
  type PinMemoryRequest,
  type RememberMemoryRequest,
  type ResolveMemoryConflictRequest,
  type MemoryApi,
} from './repository.ts'

export {
  MEMORY_EMBEDDER_SERVICE,
  MEMORY_SEMANTIC_SERVICE,
  MEMORY_VECTOR_INDEX_SERVICE,
  assertMemorySemanticGenerationCompatible,
  memoryEmbedderFingerprint,
  memoryProjectionWorkId,
  memorySemanticGenerationId,
  memoryVectorIdentityId,
  memoryVectorIndexFingerprint,
  validateMemoryEmbedderIdentity,
  validateMemoryVector,
  validateMemoryVectorIndexIdentity,
  type MemoryDistanceMetric,
  type MemoryEmbedder,
  type MemoryEmbedderIdentity,
  type MemoryProjectionOperation,
  type MemoryProjectionWork,
  type MemoryProjectionWorkState,
  type MemorySemanticFailureCode,
  type MemorySemanticGeneration,
  type MemorySemanticGenerationIdentity,
  type MemorySemanticHit,
  type MemorySemanticNeighborRelation,
  type MemorySemanticNeighborRequest,
  type MemorySemanticNeighborSuggestion,
  type MemorySemanticStatus,
  type MemorySemanticRetriever,
  type MemorySemanticSearchRequest,
  type MemoryVectorBackendKind,
  type MemoryVectorCounts,
  type MemoryVectorEntry,
  type MemoryVectorFailure,
  type MemoryVectorFilter,
  type MemoryVectorHealth,
  type MemoryVectorHit,
  type MemoryVectorIdentity,
  type MemoryVectorIndex,
  type MemoryVectorIndexIdentity,
  type MemoryVectorMaintenanceKind,
  type MemoryVectorMaintenanceOutcome,
  type MemoryVectorMaintenanceResult,
  type MemoryVectorScopeKind,
  type MemoryVectorSearchRequest,
  type MemoryVectorStatus,
} from './semantic.ts'
export {
  MemoryProjectionStore,
  memoryProjectionOwner,
  type MemoryProjectionOwner,
  type MemoryProjectionRoute,
  type MemoryProjectionGenerationTransition,
  type MemoryProjectionGenerationRecord,
  type MemoryProjectionActiveGeneration,
  type MemoryProjectionRetainedGeneration,
  type MemoryProjectionLease,
  type MemoryProjectionRebuildSource,
  type MemoryProjectionSource,
  type MemoryProjectionStatusCounts,
} from './projection-store.ts'
export {
  projectMemorySemanticQuery,
  type MemorySemanticQueryProjection,
  type MemorySemanticQueryProjectionMethod,
} from './query-projection.ts'
export {
  createMemoryCapturePlugin,
  DeterministicMemoryCandidateExtractor,
  MemoryCapturePlugin,
  type ExtractedMemoryCandidate,
  type MemoryCandidateExtractor,
  type MemoryCaptureDiagnostic,
  type MemoryCaptureMaterial,
  type MemoryCaptureNeighborSuggestion,
  type MemoryCapturePluginConfig,
  type MemoryCapturePolicy,
} from './capture.ts'
export { SqliteMemoryPlugin, SqliteMemoryPluginConfigSchema, type SqliteMemoryPluginConfig } from './sqlite.ts'
export { PostgresqlMemoryPlugin, PostgresqlMemoryPluginConfigSchema, type PostgresqlMemoryPluginConfig } from './postgresql.ts'
export type { MemoryRepository, MemoryUnitOfWork } from './repository.ts'