export { default } from './plugin.ts'
export { MemoryPlugin, MemoryPluginConfigSchema, type MemoryPluginConfig } from './plugin.ts'
export { MemoryProtocolPlugin } from './protocol.ts'
export {
  MEMORY_SCHEMA_VERSION,
  hardDeleteMemoryRecord,
  migrateMemorySchema,
  type MemoryMigrationOptions,
} from './schema.ts'
export {
  MemoryError,
  MemoryService,
  type CandidateDecisionRequest,
  type CandidateEvidenceRequest,
  type CorrectMemoryRequest,
  type ForgetMemoryRequest,
  type MemoryConflict,
  type MemoryEvidence,
  type MemoryEvidenceInput,
  type MemoryEvidenceRelation,
  type MemoryKind,
  type MemoryRecord,
  type MemoryRevision,
  type MemoryRole,
  type MemoryScope,
  type MemorySearchRequest,
  type MemorySearchResult,
  type MemoryServiceConfig,
  type MemoryStatus,
  type MemoryTemporalInput,
  type ObserveMemoryRequest,
  type PinMemoryRequest,
  type RememberMemoryRequest,
  type ResolveMemoryConflictRequest,
} from './service.ts'

export {
  MEMORY_EMBEDDER_SERVICE,
  MEMORY_SEMANTIC_SERVICE,
  MEMORY_VECTOR_INDEX_SERVICE,
  assertMemorySemanticGenerationCompatible,
  memoryEmbedderFingerprint,
  memoryProjectionWorkId,
  memorySemanticGenerationId,
  memoryVectorIdentityId,
  memoryVectorIndexFingerprint,
  validateMemoryEmbedderIdentity,
  validateMemoryVector,
  validateMemoryVectorIndexIdentity,
  type MemoryDistanceMetric,
  type MemoryEmbedder,
  type MemoryEmbedderIdentity,
  type MemoryProjectionOperation,
  type MemoryProjectionWork,
  type MemoryProjectionWorkState,
  type MemorySemanticFailureCode,
  type MemorySemanticGeneration,
  type MemorySemanticGenerationIdentity,
  type MemorySemanticHit,
  type MemorySemanticNeighborRelation,
  type MemorySemanticNeighborRequest,
  type MemorySemanticNeighborSuggestion,
  type MemorySemanticStatus,
  type MemorySemanticRetriever,
  type MemorySemanticSearchRequest,
  type MemoryVectorBackendKind,
  type MemoryVectorCounts,
  type MemoryVectorEntry,
  type MemoryVectorFailure,
  type MemoryVectorFilter,
  type MemoryVectorHealth,
  type MemoryVectorHit,
  type MemoryVectorIdentity,
  type MemoryVectorIndex,
  type MemoryVectorIndexIdentity,
  type MemoryVectorMaintenanceKind,
  type MemoryVectorMaintenanceOutcome,
  type MemoryVectorMaintenanceResult,
  type MemoryVectorScopeKind,
  type MemoryVectorSearchRequest,
  type MemoryVectorStatus,
} from './semantic.ts'
export {
  activeMemorySemanticGeneration,
  completeMemoryProjectionDeletion,
  completeMemoryProjectionUpsert,
  enqueueActiveMemoryProjection,
  enqueueKnownMemoryProjectionDeletions,
  enqueueMemoryProjectionDeletion,
  enqueueMemoryProjectionUpsert,
  enqueueMemoryRevisionReplacement,
  loadMemoryProjectionSource,
  type MemoryProjectionSource,
} from './projection-store.ts'
export {
  projectMemorySemanticQuery,
  type MemorySemanticQueryProjection,
  type MemorySemanticQueryProjectionMethod,
} from './query-projection.ts'
export {
  createMemoryCapturePlugin,
  DeterministicMemoryCandidateExtractor,
  MemoryCapturePlugin,
  type ExtractedMemoryCandidate,
  type MemoryCandidateExtractor,
  type MemoryCaptureDiagnostic,
  type MemoryCaptureMaterial,
  type MemoryCaptureNeighborSuggestion,
  type MemoryCapturePluginConfig,
  type MemoryCapturePolicy,
} from './capture.ts'